import { vueInfEdit } from "../controleur/class_inf_edit.js";
vueInfEdit.init( {
divDetail :document.querySelector('[id=div_inf_detail]')  
,edtNum :document.querySelector('[id=edt_inf_num]')  
,divTitre :document.querySelector('[id=div_inf_titre]')  
,edtDate :document.querySelector('[id=edt_inf_date]')  
,edtImmat :document.querySelector('[id=edt_inf_immat]')  
,edtPermis :document.querySelector('[id=edt_inf_permis]')  
,btnRetour :document.querySelector('[id=btn_inf_retour]')  
,btnValider :document.querySelector('[id=btn_inf_valider]')  
,btnAnnuler :document.querySelector('[id=btn_inf_annuler]')  
,lblDetailPermis :document.querySelector('[id=lbl_inf_detail_permis]')  
,lblDetailProprio :document.querySelector('[id=lbl_inf_detail_proprio]')  
,lblDetailVehic :document.querySelector('[id=lbl_inf_detail_vehic]')  
,lblNumErreur :document.querySelector('[id=lbl_erreur_num]')  
,lblDateErreur :document.querySelector('[id=lbl_erreur_date]')  
,lblImmatErreur :document.querySelector('[id=lbl_erreur_immat]')  
,lblPermisErreur :document.querySelector('[id=lbl_conduct_erreur]') 
,divInfDelit :document.querySelector('[id=div_inf_delit]')  
,divInfDelEdit:document.querySelector('[id=div_inf_delit_edit]')  
,btnAjouterDelit :document.querySelector('[id=btn_delit_ajouter]')  
,lblTotal :document.querySelector('[id=lbl_delit_total]')  
,tableDelit :document.querySelector('[id=table_delit]')  
,listeDelit :document.querySelector('[id=select_delit]')  
,btnValiderDelit :document.querySelector('[id=btn_delit_valider]')  
,btnAnnulerDelit :document.querySelector('[id=btn_delit_annuler]')  
,lblSelectDelitErreur:document.querySelector('[id=lbl_erreur_select_delit]') 
, lblDelitErreur : document.querySelector('[id=lbl_erreur_delit]')
} );